name: Words in Action
favicon: null
layout_spectrum: 0.24602965475060046
typography_spectrum: 0.7373835952021182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#abd7d6'
    - '#0e9b9a'
    - '#110505'
    - '#e39b9b'
    - '#a8403f'
  brandStrength: 0.23126315255649388
  lightness: 0.05991997616365552
  saturation: 0.7269331896677613
  rhythmicContrast: 0.1850370157044381
purpose: []
